# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec5f62a96079593c0e4d9a1916f65942e88ad4aaf59945eba4e4b6a4ecb935ecd64c676df00185a359dc1f3eb31d47f59e95412f764487ed6b3e517706f9bf67

test:
  secret_key_base: ff6b4d4290328443038713fb6e8216114e15a71298c255c2a88489fc5e05577cbdaae29b890e619d911428eaefdbdadbd5838af15a15ccb36cf76973a40f7e74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
